version: '3.7'

services:
  minio-server:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_PASSWORD=password
      - MINIO_ROOT_USER=root
    volumes:
      - "minio_data:/data"
    networks:
      - isolated

  shared-library:
    image: afekc/shared-library
    ports:
      - "4000:4000"
    environment:
      - MINIO_PORT=9000
      - MINIO_ENDPOINT=minio-server
      - MINIO_ACCESS_KEY=root
      - MINIO_SECRET_KEY=password
      - MINIO_BUCKET_NAME=bucket
    depends_on:
      - minio-server
    networks:
      - isolated

volumes:
  minio_data:

networks:
  isolated:
    internal: true